name: Build and validate
on: [ push ]

jobs:

  integration-tests:
    env:
      MERCHANT: ${{ secrets.MERCHANT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EXPLICIT_MERCHANT_SECRET_KEY: ${{ secrets.EXPLICIT_MERCHANT_SECRET_KEY }}
      EXPLICIT_MERCHANT: ${{ secrets.EXPLICIT_MERCHANT }}
    name: Integration Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ 2.6, 2.7, 3.0.3 ]
        include:
          - os: macos-latest
            ruby: 2.6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run integration tests
        run: bundle exec rake spec:integration

  rubocop:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Run style checks
        run: bundle exec rubocop